version: '3.8'

services:

  backend:
    build: ./backend/EMS.InMemoryAPI
    ports:
      - "5000:80"
    depends_on:
      - db

  frontend:
    build: ./frontend/EMPS-mvcApplication
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Strong@1234"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"